services:
  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 50000
        HOST_GID: 0
    image: ${AIRFLOW_IMAGE_NAME:-ssg-airflow:2.11.0}
    env_file:
      - .env
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 50000
        HOST_GID: 0
    image: ${AIRFLOW_IMAGE_NAME:-ssg-airflow:2.11.0}
    env_file:
      - .env
  airflow-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 50000
        HOST_GID: 0
    image: ${AIRFLOW_IMAGE_NAME:-ssg-airflow:2.11.0}
    env_file:
      - .env
  airflow-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 50000
        HOST_GID: 0
    image: ${AIRFLOW_IMAGE_NAME:-ssg-airflow:2.11.0}
    env_file:
      - .env

  airflow-triggerer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 50000
        HOST_GID: 0
    image: ${AIRFLOW_IMAGE_NAME:-ssg-airflow:2.11.0}
    env_file:
      - .env

  pg_warehouse:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ssg
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1.0'
        reservations:
          memory: 2G
          cpus: '0.5'
    volumes:
      - pg-grafan-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow_network
  # postgres:
  #  build:
  #    context: .
  #    dockerfile: postgres/Dockerfile
  #  command: ["postgres", "-c", "config_file=/usr/share/postgresql/14/postgresql.conf"]

volumes:
  pg-grafan-db-volume:
