CREATE TABLE IF NOT EXISTS general_ledger_transactions (
    id SERIAL PRIMARY KEY,
    Dated DATE,
    Vtp VARCHAR(10),
    ScrVoucher_NO VARCHAR(100),
    EntryNo NUMERIC,
    debit NUMERIC,
    credit NUMERIC,
    net NUMERIC,
    Narration TEXT,
    FinancialYear VARCHAR(10),
    CreationDate TIMESTAMP,
    account_id VARCHAR(20),
    sub_id VARCHAR(20),
    Account_Title VARCHAR(255),
    source_connection VARCHAR(255),
    root_type VARCHAR(50),
    account_type VARCHAR(50),
    Level_id1 VARCHAR(20),
    Upper_Level_1_Title VARCHAR(255),
    Level_id2 VARCHAR(20),
    Upper_Level_2_Title VARCHAR(255),
    TypeOfID NUMERIC(1),
    LevelNo NUMERIC(1),
    VoucherDate DATE,
    Prp_Date DATE,
    Prp_ID VARCHAR(50),
    ChqDate DATE,
    ChqClearanceDate DATE,
    Chk_Date DATE,
    ChqNo VARCHAR(50),
    ChallanNo VARCHAR(50),
    CancellDate DATE,
    CancelledBy VARCHAR(50),
    atp2_ID VARCHAR(50)
);